language: node_js
node_js:
  - "node"
  - "lts/*"
  - "14"
os:
  - linux
  - osx
  - windows

install:
- |-
  case $TRAVIS_OS_NAME in
    windows)
      npm install rimraf --global
      npm install
    ;;
    *)
      make installGlobal
      make install
    ;;
  esac

cache:
  npm: true

script:
  - npm start
