name: build-README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: npm start
        env:
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: Push new README.md
        run: |
         echo "GITHUB_ACTOR -> ${GITHUB_ACTOR}"
         echo "GITHUB_REPOSITORY -> ${GITHUB_REPOSITORY}"
         COMMIT_MSG="update README.md by github action at cron set"
         if [ -z "${COMMIT_MSG}" ]; then
          echo "error: not found env: COMMIT_MSG"
          exit 1
         fi
         echo "COMMIT_MSG -> ${COMMIT_MSG}"
         # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
         remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
         git config http.sslVerify false
         git config user.name "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         git remote add publisher "${remote_repo}"

         # useful for debugging
         git show-ref
         git branch --verbose

         # install lfs hooks
         git lfs install

         # publish any new files
         git checkout main
         git add -A
         git commit -m "${COMMIT_MSG}" || exit 0
         git pull --rebase publisher main
         git push publisher main