name: build-README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: npm start
        env:
          RUN_MODE: ${{secrets.RUN_MODE}}
          OPEN_WEATHER_MAP_KEY: ${{secrets.OPEN_WEATHER_MAP_KEY}}
      - name: Commit files
        run: |
         echo "GITHUB_ACTOR -> ${GITHUB_ACTOR}"
         echo "GITHUB_REPOSITORY -> ${GITHUB_REPOSITORY}"
         COMMIT_MSG="Updated the Graph with weather data, by github action at cron set"
         if [ -z "${COMMIT_MSG}" ]; then
          echo "error: not found env: COMMIT_MSG"
          exit 1
         fi
         # wait node file write
         sleep 3
         git config http.sslVerify false
         git config user.name "${GITHUB_ACTOR}"
         git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
         # commit
         git commit -m '${COMMIT_MSG}' --all
         # see status
         git status
      - name: Push new README.md
        uses: ad-m/github-push-action@v0.6.0 # https://github.com/ad-m/github-push-action#github-action-for-github-push
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Repository name to push. Default or empty value represents current github repository ( ${{ GITHUB_REPOSITORY }} )
          repository: ${{ GITHUB_REPOSITORY }}
          # Destination branch to push changes, optional, default is master
          branch: ${{ github.ref }}
          # Determines if force push is used
          #force: false
          # Determines if --tags is used
          #tags: false
          # Directory to change to before pushing. optional, default is .
          #directory: '.'